---
title: "dataCleaning2"
author: "Hunter Wright"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

```{r setup & load packages, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(pacman)
p_load(dplyr, broom, ggplot2, tidyverse, readr, purrr, tidyr, gtools, fuzzyjoin)
```

```{r rename files in directory, eval=FALSE, include=FALSE}
parent_dir <- "membershipData" 

dirs <- list.dirs(parent_dir, recursive = FALSE)

for (d in dirs) {
  csvs <- list.files(d, pattern = "\\.csv$", full.names = TRUE)
  
  new_names <- sprintf("week%d.csv", seq_along(csvs))
  
  file.rename(csvs, file.path(d, new_names))
}
```


```{r membership function}

clean <- function(file_path,
                  expected_cols = c("Date", 
                       "No Membership Total",
                       "Alumni Members Total",
                       "Community Members Total",
                       "Current Student Total",
                       "Current Student 1 Total",
                       "Faculty & Staff Total",
                       "PE & Rec Staff Total",
                       "Class MWF Total",
                       "Class TU/TR Total",
                       "Club Sports - Limited Total",
                       "Club Sports- Limited Total",             
                       "Guest Pass Total",                        
                       "Community Membership Total",        
                       "Club Sports- Basketball - Limited Hours Total",        
                       "Club Sport Fencing - Limited Hours Total",             
                       "Club Sports - Wushu - Limited Hours Total",            
                       "Club Sports- W Water Polo- Limited Hours Total",       
                       "Athletics - Tennis Total",                             
                       "Club Sports - Jiu Jitsu - Limited Hours Total",        
                       "Club Sports - Swim - Limited Hours Total",             
                       "Faculty/Staff Total",                                  
                       "NCU Semester Membership Total",                        
                       "Spouse/Dependent Total",                               
                       "Student Off Term Total",                               
                       "NCU Total",                                            
                       "Class MW Total",                                       
                       "Dependent/Spouse Total",                               
                       "Club Sports- Wrestling - Limited Hours Total",         
                       "PE Volunteer MTWThF Total",                            
                       "Class MTWTh Total",                                    
                       "Club Sports - Dance - Limited Hours Total",            
                       "PE Volunteer MW Total",                                
                       "PE MW Total",                                          
                       "SRC Access for IM Participants Total",                 
                       "Spring 2021 - Faculty/Staff GX Turnstile Access Total",
                       "Worlds 2022 Staff Membership Total",                   
                       "Winter 2021 - Faculty/Staff GX Turnstile Access Total",
                       "PE T/R Total",                                         
                       "Bushnell Total",                                       
                       "Club Sports - Kendo - Limited Hours Total",            
                       "Courtesy Total",                                       
                       "Club Sports - Kendo Total",                            
                       "Bushnell Semester Membership Total",                   
                       "Club Sports - Weightlifting - Limited Hours Total",    
                       "Club Sports Hockey Total",                             
                       "PE Volunteer M/W Total")) {
 
  #read in csv
  raw <- read_csv(file_path, col_names = FALSE, show_col_types = FALSE)

  raw <- raw %>%
    relocate("X2", .after = "X8")
  
  date_range <- raw[[1]][3] #date range is in row 3 column 1
  
  #example: "Mon, Jan 5, 2015 12:00 AM to Sun, Jan 11, 2015 11:59 PM"
  date_parts <- strsplit(date_range, " to ")[[1]] #split at "to"
  
  #remove day and time
  #gsub: ^start from beginning, [^,]+ match one or more chars that are not a comma, \\s*   match a comma followed by whitespace
  start_date <- as.Date(trimws(gsub("^[^,]+,\\s*", "", #removes day
                  sub(" 12:00 AM", "", date_parts[1]))), #remove 12:00 AM from first part   of vector
                  format = "%b %d, %Y") #convert to R date object
  
  #initialize week dates
  week_dates <- seq(start_date, by = "day", length.out = 7)
  
  #identifying membership totals rows and names
  
  #return vector of rows that start with "Membership Totals:"
  totals_idx <- which(grepl("^Membership Totals:", raw[[1]]))
  
  #get the corresponding membership type rows
  #the last "Membership Type:" row preceding each totals row)
  type_idx <- which(grepl("^Membership Type:", raw[[1]])) #mem type vector
  membership_names <- c() #create vector to store names
  for (ti in totals_idx) { #iterate over each row index ti where the totals for a membership are recorded
    preceding <- type_idx[type_idx < ti] #find all rows from type_idx that come before the current totals row ti
    if (length(preceding) > 0) { #check if there is at least one membership type row  before the totals row
      last_type <- max(preceding) #pick the last membership type row 
      mem_name <- trimws(sub("Membership Type:", "", raw[[1]][last_type]))
      membership_names <- c(membership_names, paste(mem_name, "Total"))
    } else {
      membership_names <- c(membership_names, NA)
    }
  }

  days_row <- raw[5, ] #create vector of days of the week
  
  data_rows <- bind_rows(days_row, raw[totals_idx, ]) #combine with totals 
  
  data_rows <- data_rows %>% 
    select(-1) #remove unneeded columns
  
  data_rows <- data_rows %>% 
    select(1:7) #keep the 7 columns corresponding to the days
  
  #replace the day names row with dates
  data_rows[1, ] <- as.list(format(week_dates, "%Y-%m-%d"))
  
  #transpose
  df <- as.data.frame(t(data_rows), stringsAsFactors = FALSE)
  
  #name columns
  colnames(df) <- c("Date", membership_names)
  
  #add NAs for missing columns
  for (mem in expected_cols) {
    if (!(mem %in% colnames(df))) {
      df[[mem]] <- NA
    }
  }
  
  return(df)
}

```
```{r create membership df}

#create list of years
years <- list.files("membershipData", full.names = TRUE)

#combine
membership_dirty <- map_dfr(years, function(folder) {
  files <- list.files(folder, pattern = "week\\d+\\.csv", full.names = TRUE)
  map_dfr(files, clean)
}) %>% 
  arrange(Date)

membership_dirty <- membership_dirty %>%
  mutate(Date = as.Date(Date, format = "%Y-%m-%d"), #date column as Date type
         across(-Date, as.numeric)) %>% #set all columns to numeric
  complete(Date = seq(min(Date), max(Date), by = "day")) %>% #add missing days
  mutate(across(-Date, ~ replace_na(., 0))) #replace NAs with 0s

#remove junk columns and create other column, total column
membership <- membership_dirty %>%
  rename(date = Date,
         nonmembers = "No Membership Total",
         alumni = "Alumni Members Total",
         community_members1 = "Community Members Total",
         students = "Current Student Total",
         col1 = "Current Student 1 Total",
         faculty_and_staff = "Faculty & Staff Total",
         pe_staff = "PE & Rec Staff Total",
         col2 = "Class MWF Total",                                      
         col3 = "Class TU/TR Total",                                    
         col4 = "Club Sports - Limited Total",                          
         col5 = "Club Sports- Limited Total",                           
         col6 = "Guest Pass Total",                                     
         col7 = "Community Membership Total",                         
         col8 = "Club Sports- Basketball - Limited Hours Total",        
         col9 = "Club Sport Fencing - Limited Hours Total",             
         col10 = "Club Sports - Wushu - Limited Hours Total",            
         col11 = "Club Sports- W Water Polo- Limited Hours Total",       
         col12 = "Athletics - Tennis Total",                             
         col13 = "Club Sports - Jiu Jitsu - Limited Hours Total",        
         col14 = "Club Sports - Swim - Limited Hours Total",
         col15 = "Faculty/Staff Total",
         col16 = "NCU Semester Membership Total",                        
         col17 = "Spouse/Dependent Total",                               
         student_offterm = "Student Off Term Total",                          
         col19 = "NCU Total",                                            
         col20 = "Class MW Total",                                       
         col21 = "Dependent/Spouse Total",                               
         col22 = "Club Sports- Wrestling - Limited Hours Total",         
         col23 = "PE Volunteer MTWThF Total",                            
         col24 = "Class MTWTh Total",                                    
         col25 = "Club Sports - Dance - Limited Hours Total",            
         col26 = "PE Volunteer MW Total",                                
         col27 = "PE MW Total",                                          
         col28 = "SRC Access for IM Participants Total",                 
         col29 = "Spring 2021 - Faculty/Staff GX Turnstile Access Total",
         col30 = "Worlds 2022 Staff Membership Total",                   
         col31 = "Winter 2021 - Faculty/Staff GX Turnstile Access Total",
         col32 = "PE T/R Total",                                         
         col33 = "Bushnell Total",                                       
         col34 = "Club Sports - Kendo - Limited Hours Total",            
         col35 = "Courtesy Total",                                       
         col36 = "Club Sports - Kendo Total",                            
         col37 = "Bushnell Semester Membership Total",                   
         col38 = "Club Sports - Weightlifting - Limited Hours Total",    
         col39 = "Club Sports Hockey Total",                             
         col40 = "PE Volunteer M/W Total"
         ) %>%
  mutate(other = col2 + col3 + col4 + col5  + col6 + col8  + col9  + col10 + col11 + col12 + col13 + col14 + col16 + col17 + col19 + col20 + col21 + col22 + col23 + col24 + col25 + col26 + col27 + col28 + col29 + col30 + col31 + col32 + col33 + col34 + col35 + col36 + col37 + col38 + col39 + col40,
        faculty_staff = faculty_and_staff + col15,
        community_members = community_members1 + col7,
        total = nonmembers + alumni + faculty_staff + community_members + students + student_offterm + pe_staff + other) %>%
  select(date, students, student_offterm, alumni, nonmembers, community_members, faculty_staff, pe_staff, other, total)

```
```{r count function}
cleanCount <- function(file_path,
                  expected_cols = c("Date", "5:00AM",
                                            "6:00AM",
                                            "7:00AM",
                                            "8:00AM",
                                            "9:00AM",
                                            "10:00AM",
                                            "11:00AM",
                                            "12:00PM",
                                            "1:00PM",
                                            "2:00PM",
                                            "3:00PM",
                                            "4:00PM",
                                            "5:00PM",
                                            "6:00PM",
                                            "7:00PM",
                                            "8:00PM",
                                            "9:00PM",
                                            "10:00PM",
                                            "11:00PM")) {
 
  #read in csv
  raw <- read_csv(file_path, col_names = FALSE, show_col_types = FALSE)
  
  date_range <- raw[[1]][3] #date range is in row 3 column 1
  
  #example: "Mon, Jan 5, 2015 12:00 AM to Sun, Jan 11, 2015 11:59 PM"
  date_parts <- strsplit(date_range, " to ")[[1]] #split at "to"
  
  #remove day and time
  
  #gsub: ^start from beginning, 
  #     [^,]+ match one or more chars that are not a comma, 
  #     \\s* match a comma followed by white space
  start_date <- as.Date(trimws(gsub("^[^,]+,\\s*", "", #removes day
  #remove 12:00 AM from first part of vector                
                               sub(" 12:00 AM", "", date_parts[1]))),
  #convert to R date object
                               format = "%b %d, %Y") 
  
  #initialize week dates
  week_dates <- seq(start_date, by = "day", length.out = 7)
  
  #return vector of rows that start contain a dash "-"
  hours_idx <- which(grepl("-", raw[[1]]))
  
  names <- c()
  for(i in hours_idx) {
    name <- trimws(gsub("-.*", "", raw[[1]][i]))
    names <- c(names, name)
  }

  days_row <- raw[5, ] #create vector of days of the week
  
  data_rows <- bind_rows(days_row, raw[hours_idx, ]) #combine
  
  #replace the day names row with dates
  data_rows[1, 2:8] <- as.list(format(week_dates, "%Y-%m-%d"))
  
  #transpose
  df <- as.data.frame(t(data_rows))
  
  #name columns
  colnames(df) <- c("Date", names)
  
  df <- df %>%
    slice(-1, -9)
  
  #add NAs for missing columns
  for (i in expected_cols) {
    if (!(i %in% colnames(df))) {
      df[[i]] <- NA
    }
  }
  
  return(df)
}

```
```{r create count df}

#create list of years
yearsCount <- list.files("countData", full.names = TRUE)

#combine
count <- map_dfr(yearsCount, function(folder) {
  files <- list.files(folder, pattern = "week\\d+\\.csv", full.names = TRUE)
  map_dfr(files, cleanCount)
}) %>% 
  arrange(Date)

count <- count %>%
  mutate(Date = as.Date(Date, format = "%Y-%m-%d"), #date column as Date type
         across(-Date, as.numeric)) %>% #set all columns to numeric
  complete(Date = seq(min(Date), max(Date), by = "day")) %>% #add missing days
  mutate(across(-Date, ~ replace_na(., 0))) #replace NAs with 0s

count <- count %>%
  relocate("5:00AM", .before = "9:00AM") %>%
  relocate("6:00AM", .after = "5:00AM") %>%
  relocate("7:00AM", .after = "6:00AM") %>%
  relocate("8:00AM", .after = "7:00AM") %>%
  relocate("6:00AM", .after = "5:00AM") %>%
  relocate("5:00PM", .after = "4:00PM") %>%
  relocate("6:00PM", .after = "5:00PM") %>%
  relocate("5:00PM", .after = "4:00PM") %>%
  mutate(total = rowSums(count[, -1]))


```

```{r rename count columns}

count <- count %>%
  rename(am5 = "5:00AM", 
         am6 = "6:00AM", 
         am7 = "7:00AM", 
         am8 = "8:00AM",
         am9 = "9:00AM", 
         am10 = "10:00AM", 
         am11 = "11:00AM", 
         pm12 = "12:00PM", 
         pm1 = "1:00PM", 
         pm2 = "2:00PM", 
         pm3 = "3:00PM", 
         pm4 = "4:00PM", 
         pm5 = "5:00PM", 
         pm6 = "6:00PM", 
         pm7 = "7:00PM", 
         pm8 = "8:00PM", 
         pm9 = "9:00PM", 
         pm10 = "10:00PM", 
         pm11 = "11:00PM")
```

```{r add rows to finish 2024}

count <- count %>%
  mutate(date = as.Date(Date, format = "%Y-%m-%d")) %>% 
  select(-Date) %>%
  filter(!is.na(date)) %>%
  complete(
    date = seq(
      min(date, na.rm = TRUE),
      as.Date("2024-12-31"),
      by = "day"
    )
  ) %>%
  mutate(across(where(is.numeric), replace_na, 0))

membership <- membership %>%
  mutate(date = as.Date(date, format = "%Y-%m-%d")) %>% 
  filter(!is.na(date)) %>%
  complete(
    date = seq(
      min(date, na.rm = TRUE),
      as.Date("2024-12-31"),
      by = "day"
    )
  ) %>%
  mutate(across(where(is.numeric), replace_na, 0))
```

```{r weekday column + weekend, covid, closure dummies}

# create weekday column
members <- membership %>%
  mutate(day = weekdays(as.Date(date))) %>%
  relocate( day, .after = date) 
count <- count %>%
  mutate(day = weekdays(as.Date(date))) %>%
  relocate( day, .after = date)

# weekday/weekend dummy
members <- members %>%
  mutate(weekend = ifelse(day == "Saturday" | day == "Sunday", 1, 0))
count <- count %>%
  mutate(weekend = ifelse(day == "Saturday" | day == "Sunday", 1, 0))

# covid dummy
members <- members %>%
  mutate(covid = ifelse("2020-03-18" <= date & date < "2021-09-27", 1, 0))
count <- count %>%
  mutate(covid = ifelse("2020-03-18" <= date & date < "2021-09-27", 1, 0))

#closed dummy (total entrances = 0)
members <- members %>%
  mutate(closed = ifelse(students == 0, 1, 0)) #no students: probably closed
count <- count %>%
  mutate(closed = ifelse(total < 10, 1, 0)) # account for closures with pe_staff present

#day after closed dummy
members <- members %>%
  mutate(day_after_closed = ifelse(lag(closed) == 1, 1, 0))
members[1, "day_after_closed"] <- 0

count <- count %>%
  mutate(day_after_closed = ifelse(lag(closed) == 1, 1, 0))
count[1, "day_after_closed"] <- 0

#closure numbers within 20 observations of each other
members %>%
  filter(students == 0) %>%
  nrow() #655

count %>%
  filter(total < 10) %>%
  nrow() #672
```
```{r finals dummy}
.finals <- tribble( #create df of finals week dates
  ~year,   ~start,       ~end,
  2015, "2015-12-07", "2015-12-11",
  2016, "2016-12-05", "2016-12-09",
  2017, "2017-12-04", "2017-12-08",
  2018, "2018-12-03", "2018-12-07",
  2019, "2019-12-09", "2019-12-13",
  2020, "2020-12-07", "2020-12-11",
  2021, "2021-12-06", "2021-12-10",
  2022, "2022-12-05", "2022-12-09",
  2023, "2023-12-04", "2023-12-08",
  2024, "2024-12-09", "2024-12-13",
  2015, "2015-03-16", "2015-03-20",
  2016, "2016-03-14", "2016-03-18",
  2017, "2017-03-20", "2017-03-24",
  2018, "2018-03-19", "2018-03-23",
  2019, "2019-03-18", "2019-03-22",
  2020, "2020-03-16", "2020-03-20",
  2021, "2021-03-15", "2021-03-19",
  2022, "2022-03-14", "2022-03-18",
  2023, "2023-03-20", "2023-03-24",
  2024, "2024-03-18", "2024-03-22",
  2015, "2015-06-08", "2015-06-12",
  2016, "2016-06-06", "2016-06-10",
  2017, "2017-06-12", "2017-06-16",
  2018, "2018-06-11", "2018-06-15",
  2019, "2019-06-10", "2019-06-14",
  2020, "2020-06-08", "2020-06-12",
  2021, "2021-06-07", "2021-06-11",
  2022, "2022-06-06", "2022-06-10",
  2023, "2023-06-12", "2023-06-16",
  2024, "2024-06-10", "2024-06-14"
) %>%
  mutate(across(start:end, as.Date)) #convert to date objects

.deadweek <- .finals %>% #create dead week df
  mutate(
    start = start - 7, #monday before finals
    end   = end   - 5) #sunday before finals

.finalsDead <- bind_rows( #combine into one df
  .finals %>% mutate(finals_week = 1, dead_week = 0), #finals 1, deadweek 0
  .deadweek %>% mutate(finals_week = 0, dead_week = 1) #finals 0, deadweek 1
)

members <- members %>% #add to main data
  mutate(date = as.Date(date)) %>%
  left_join(.finalsDead,
            join_by(between(date, start, end))) %>%
  mutate(
    finals_week = coalesce(finals_week, 0L),
    dead_week   = coalesce(dead_week,   0L)
  ) %>%
  select(-year, -start, -end) #remove unneeded cols

count <- count %>% #repeat for other data
  mutate(date = as.Date(date)) %>%
  left_join(.finalsDead,
            join_by(between(date, start, end))) %>%
  mutate(
    finals_week = coalesce(finals_week, 0L),
    dead_week   = coalesce(dead_week,   0L)
  ) %>%
  select(-year, -start, -end)

count <- count %>%
  select(-am5) #remove 5am col (rec normally closed at this hour)

```

```{r add quarter, week of quarter, month to count }
count <- count %>%
  filter(date > "2015-01-04")

quarters <- tribble(
  ~quarter, ~start,        ~end,
  #2015
  "Winter", "2015-01-05", "2015-03-20",
  "Spring", "2015-03-30", "2015-06-12",
  "Summer", "2015-06-13", "2015-09-04",
  "Fall",   "2015-09-28", "2015-12-11",
  #2016
  "Winter", "2016-01-04", "2016-03-18",
  "Spring", "2016-03-28", "2016-06-10",
  "Summer", "2016-06-20", "2016-09-09", 
  "Fall",   "2016-09-26", "2016-12-09",
  #2017
  "Winter", "2017-01-09", "2017-03-24",
  "Spring", "2017-04-03", "2017-06-16",
  "Summer", "2017-06-26", "2017-09-15",
  "Fall",   "2017-09-25", "2017-12-08",
  #2018
  "Winter", "2018-01-08", "2018-03-23",
  "Spring", "2018-04-02", "2018-06-16",
  "Summer", "2018-06-25", "2018-09-14",
  "Fall",   "2018-09-24", "2018-12-07",
  #2019
  "Winter", "2019-01-07", "2019-03-22",
  "Spring", "2019-04-01", "2019-06-14",
  "Summer", "2019-06-24", "2019-09-13",
  "Fall",   "2019-10-01", "2019-12-13",
  #2020
  "Winter", "2020-01-06", "2020-03-20",
  "Spring", "2020-03-30", "2020-06-12",
  "Summer", "2020-06-22", "2020-09-11",
  "Fall",   "2020-09-29", "2020-12-11",
  #2021
  "Winter", "2021-01-04", "2021-03-19",
  "Spring", "2021-03-29", "2021-06-11",
  "Summer", "2021-06-21", "2021-09-10",
  "Fall",   "2021-09-27", "2021-12-10",
  #2022
  "Winter", "2022-01-03", "2022-03-18",
  "Spring", "2022-03-28", "2022-06-10",
  "Summer", "2022-06-20", "2022-09-09",
  "Fall",   "2022-09-27", "2022-12-13",
  #2023
  "Winter", "2023-01-09", "2023-03-24",
  "Spring", "2023-04-03", "2023-06-16",
  "Summer", "2023-06-26", "2023-09-15",
  "Fall",   "2023-09-26", "2023-12-08",
  #2024
  "Winter", "2024-01-08", "2024-03-22",
  "Spring", "2024-04-01", "2024-06-14",
  "Summer", "2024-06-24", "2024-09-13",
  "Fall",   "2024-09-30", "2024-12-13"
) %>%
  mutate(across(start:end, as.Date))

#join every gym‑date to the quarter it falls in
count_aug <- fuzzy_left_join(
  count, 
  quarters,
  by = c("date" = "start", 
         "date" = "end"), 
  match_fun = list(`>=`, `<=`)
) %>%
  mutate( #add week of quarter and calendar month
    week_of_quarter = as.integer(floor((date - start) / 7) + 1L),  #starts at 1
    month           = month(date, label = TRUE, abbr = FALSE)
  ) %>%
  select(-start, -end)

#add in label for between quarter dates
count_aug <- count_aug %>% 
  mutate(
    quarter = coalesce(quarter, "Break"),
    week_of_quarter = if_else(is.na(week_of_quarter), 0L, week_of_quarter)
  )

count <- count_aug %>%
  relocate(month, .after = date) %>%
  relocate(quarter, .after = day) %>%
  relocate(week_of_quarter, .after = quarter) %>%
  rename(week = week_of_quarter)
```

```{r add quarter, week of quarter, month to members}
members <- members %>%
  filter(date > "2015-01-04")

#join every gym‑date to the quarter it falls in
members_aug <- fuzzy_left_join(
  members,
  quarters,
  by = c("date" = "start", 
         "date" = "end"), 
  match_fun = list(`>=`, `<=`)
) %>%
  mutate( #add week of quarter and calendar month
    week_of_quarter = as.integer(floor((date - start) / 7) + 1L),  #starts at 1
    month           = month(date, label = TRUE, abbr = FALSE)
  ) %>%
  select(-start, -end)

#add in label for between quarter dates
members_aug <- members_aug %>% 
  mutate(
    quarter = coalesce(quarter, "Break"),
    week_of_quarter = if_else(is.na(week_of_quarter), 0L, week_of_quarter)
  )

members <- members_aug %>%
  relocate(month, .after = date) %>%
  relocate(quarter, .after = day) %>%
  relocate(week_of_quarter, .after = quarter) %>%
  rename(week = week_of_quarter)
```



```{r write csv}
write.csv(members, "cleanData/membership.csv", row.names = FALSE)
write.csv(count, "cleanData/count.csv", row.names = FALSE)
```



