---
title: "University of Oregon Gym Attendance: An Analysis of Student Behavior and Decision Making"
author: "Hunter Wright"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(pacman)
p_load(tidyverse, forcats, kableExtra)

count <- read.csv("cleanData/count.csv")
members <- read.csv("cleanData/membership.csv")

```
```{r factor releveling, covid removed df}
members <- members %>%
  mutate(day = fct_relevel(day, "Monday"))
count <- count %>%
  mutate(day = fct_relevel(day, "Monday"))

count_no_covid <- count %>%
  filter(covid == 0)
```

# Introduction

```{r Attendance Plot}
plot2024 <- count %>%
  mutate(year = year(date)) %>%
  filter(year == 2024) %>%
  mutate(week = floor_date(date, "week", week_start = 1)) %>%
  group_by(week) %>% 
  summarise(avg_total = mean(total, na.rm = TRUE), .groups = "drop") %>% 
  ggplot(aes(week, avg_total)) +
  geom_line() +
    labs(x = "Time",
         y = "Average Daily Visits",
         title = "Weekly Average Gym Attendance – 2024") +
  theme_bw()
plot2024
```

# Background



# Data

```{r summary statistics table}
summary_stats <- count %>%
  summarise(
    Mean = mean(total),
    Median = median(total),
    SD = sd(total),
    Min = min(total),
    Max = max(total)
  )

kable(summary_stats, caption = "Summary Statistics") %>%
  kable_styling(full_width = FALSE) %>%
  row_spec(0, align = "c") %>%
  row_spec(1, align = "c")
```

# Methods



# Results
```{r first regression}
test2 <- lm(total ~ day + closed + day_after_closed + finals_week + dead_week, count_no_covid)

summary(test2)
```


# Conclusion
















